apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: testflask-listener
  namespace: testflask-cicd
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: pipeline-binding
        - kind: TriggerBinding
          ref: message-binding
      name: my-trigger
      template:
        ref: pipeline-template
